#!/bin/bash

DBDIR="../rw/db"
SESSIONSDIR="$DBDIR/sessions"
USERSDIR="$DBDIR/users"
SHITSDIR="$DBDIR/shitposts"
FOLLOWERSDIR="$DBDIR/followers"
HASHTAGSDIR="$DBDIR/hashtags"

STATICDIR="./static"
TEMPLATESDIR="./templates"


mkdir -p "$SESSIONSDIR" "$USERSDIR" "$STATICDIR" "$TEMPLATESDIR" "$SHITSDIR" "$FOLLOWERSDIR" "$HASHTAGSDIR"