version: '3.6'
services:
  shittr-backend:
    build: .
    image: dockerreg.enowars.com:5000/shittr-backend
    networks:
     - bridge
     - enoverlay
    environment:
     - MONGO_ENABLED=1
     - MONGO_HOST=shittr-db
     - MONGO_PORT=27017
     - MONGO_USER=ipv6islove
     - MONGO_PASSWORD=dockerislove
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=shittr-checker"
        - "traefik.docker.network=enoverlay"
        - "traefik.frontend.rule=Host:shittr.checker.enowars.com,service8.checker.enowars.com,8454.checker.enowars.com"
        - "traefik.port=3031"
      replicas: 2
#      placement:
#        constraints:
#          - "node.hostname!=mainvm"
  shittr-db:
    image: mongo
    networks:
      - enoverlay
    volumes:
      - shittr_db_data:/data/db
#we need to fix the node otherwise the volumes are lost after migration :/
    deploy:
      placement:
        constraints:
          - "node.hostname==c11"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ipv6islove
      MONGO_INITDB_ROOT_PASSWORD: dockerislove


networks:
  bridge:
    external: true
  enoverlay:
    external: true
volumes:
  shittr_db_data:

